

train:
    seed: 42
    epochs: 120
    lr: 1e-3
    batch_size: 16
    num_workers: 8
    folds: [1, 2, 3, 4, 5]
    patience: ${train.epochs} # No early stopping (patience == epochs)
    use_wavgram_logmel: false
    use_amp: false

model:
    encoder : "tf_efficientnet_b0_ns"
    sample_rate: 32000
    window_size: 1024
    hop_size: 320
    mel_bins: 128
    fmin: 0
    fmax: 16000
    encoder_features_num: 1280
    embedding_dim: 2048
    imagenet_pretrained: true
    class_num: 50

data:
    mixup_alpha: .5
    step_scheduler: true
    use_mixup: false
    use_specaug: false
    output_dir: weights/${model.encoder}-${model.imagenet_pretrained}_imagenet-${data.use_mixup}_mixup-${data.use_specaug}_specaug-${train.use_wavgram_logmel}_wavgram_logmel
    data_path: data/ESC-50-master/audio
    metadata_path: data/ESC-50-master/meta/esc50.csv
    preloaded_data_path: preloaded_data/ESC-50

command: ??? # Possible options: train, test

defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

